apiVersion: v1
kind: Secret
metadata:
  name: hearo-backend-secret
type: Opaque
stringData:
  db-url: jdbc:mysql://your-rds-endpoint.ap-northeast-2.rds.amazonaws.com:3306/hearO?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  db-username: 
  db-password: 
  mail-username: wnsgud0566@gmail.com
  mail-password: hearO0227&
  jwt-secret: dev-only-jwt-secret-change-this-before-production-1234567890
  clova-speech-secret: 30114c74057941c8af8d57f5414c759c
  clova-speech-invoke-url: https://clovaspeech-gw.ncloud.com/external/v1/16178/94f66cf09b0cd1e7bba34811be10a35b9bad3ce60808e49f183b0cad532fc554
