apiVersion: v1
kind: Secret
metadata:
  name: hearo-backend-secret
type: Opaque
stringData:
  db-url: jdbc:mysql://your-rds-endpoint.ap-northeast-2.rds.amazonaws.com:3306/hearO?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  db-username: change-me
  db-password: change-me
  mail-username: change-me
  mail-password: change-me
  jwt-secret: change-me
  clova-speech-secret: change-me
  clova-speech-invoke-url: change-me
